site_name: test
site_url: https://systemc.org/

repo_url: https://github.com/accellera-official/systemc/

theme:
  name: mkdocs
  custom_dir: overrides/
  nav_style: light

extra_css:
  - stylesheets/extra.css

nav:
- Home: 'index.md'
- Overview: 
    - 'SystemC': 'overview/systemc.md' 
    - 'SystemC AMS': 'overview/systemc-ams.md' 
- Community:
    - Events:
      - 'SystemC Evolution Events': 'events/scevents.md'
      - 'SystemC Evolution Fika - 7 April 2022': 'events/scef202204.md'
      - 'SystemC Evolution Fika - June 2021': 'events/scef202106.md'
      - 'SystemC Evolution Fika - March 2021': 'events/scef202103.md'
      - 'SystemC Evolution Day 2021': 'events/sced2021.md'
      - 'SystemC Evolution Day 2020': 'events/sced2020.md'
      - 'SystemC Evolution Day 2019': 'events/sced2019.md'
      - 'SystemC Evolution Day 2018': 'events/sced2018.md'
      - 'SystemC Evolution Day 2017': 'events/sced2017.md'
      - 'SystemC Evolution Day 2016': 'events/sced2016.md'

    - Discussion forum: https://forums.accellera.org/forum/9-systemc/
- Resources:
    - 'Books': 'resources/books.md'
    - 'Education': 'resources/education.md'
    - 'Libraries & Projects': 'resources/projects.md'
    - 'Standards & Implementations': 'resources/standards.md' 
    - 'Tools': 'resources/tools.md'
    - 'Training': 'resources/training.md'
    - 'Videos': 'resources/videos.md' 
- Playground: https://www.edaplayground.com/x/56Q4 
- About: 'about.md'

