site_name: test
site_url: https://systemc.org/

repo_url: https://github.com/accellera-official/systemc/

theme:
  name: mkdocs
  custom_dir: overrides/
  nav_style: light

extra_css:
  - stylesheets/extra.css

nav:
- Home: 'index.md'
- Overview: 
    - 'SystemC': 'overview/systemc.md' 
    - 'SystemC AMS': 'overview/systemc-ams.md' 
- Downloads: 'downloads.md' 
- Resources:
    - 'Videos': 'resources/videos.md' 
    - 'Books': 'resources/books.md'
    - 'Training': 'resources/training.md'
    - 'Projects': 'resources/projects.md'
- Events:
    - 'SystemC Evolution Day 2021': 'events/sced2021.md'
- Forums: https://forums.accellera.org/forum/9-systemc/
- About: 'about.md'

