site_name: test
site_url: http://systemc.org/

repo_url: https://github.com/accellera-official/systemc/

theme:
  name: mkdocs
  custom_dir: overrides/
  nav_style: light

extra_css:
  - stylesheets/extra.css

nav:
- Home: 'index.md'
- Downloads: 'downloads.md' 
- Events:
    - 'SystemC Evolution Day 2021': 'events/sced2021.md'
- About: 'about.md'
